# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171110_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='q_test',
            new_name='question',
        ),
    ]
